[config]
version_check = false

[templates.hyprland]
input_path = "~/.config/matugen/templates/dark/colors-hyprland.conf"
output_path = "~/.cache/dotfiles/colors_hyprland.conf"
post_hook = "hyprctl reload"

[templates.kitty]
input_path = "~/.config/matugen/templates/dark/colors-kitty.conf"
output_path = "~/.cache/dotfiles/colors-kitty.conf"
post_hook = "pkill -SIGUSR1 kitty"

[templates.swaync]
input_path = "~/.config/matugen/templates/dark/colors-swaync.css"
output_path = "~/.cache/dotfiles/colors-swaync.css"
post_hook = 'swaync-client -rs'

[templates.waybar]
input_path = "~/.config/matugen/templates/dark/colors-waybar.css"
output_path = "~/.cache/dotfiles/colors-waybar.css"
# post_hook = "killall waybar && waybar &"
post_hook = 'pkill -SIGUSR2 waybar'
