[config]
version_check = false

[templates.hyprland]
input_path = "~/.config/matugen/templates/dark/hyprtheme.conf"
output_path = "~/.cache/dotfiles/hyprtheme.conf"
post_hook = "hyprctl reload"

[templates.kitty]
input_path = "~/.config/matugen/templates/dark/colors-kitty.conf"
output_path = "~/.cache/dotfiles/colors-kitty.conf"
post_hook = "pkill -SIGUSR1 kitty"

[templates.mako]
input_path = "~/.config/matugen/templates/dark/colors_mako.conf"
output_path = "~/.cache/dotfiles/colors_mako.conf"
post_hook = "systemctl --user restart mako"

[templates.rofi]
input_path = "~/.config/matugen/templates/dark/colors-rofi.rasi"
output_path = "~/.cache/dotfiles/colors-rofi.rasi"

[templates.swaync]
input_path = "~/.config/matugen/templates/dark/colors-swaync.css"
output_path = "~/.cache/dotfiles/colors-swaync.css"
post_hook = 'swaync-client -rs'

[templates.waybar]
input_path = "~/.config/matugen/templates/dark/colors-waybar.css"
output_path = "~/.cache/dotfiles/colors-waybar.css"
# post_hook = "killall waybar && waybar &"
post_hook = 'pkill -SIGUSR2 waybar'

[templates.wezterm]
input_path = "~/.config/matugen/templates/dark/colors_wezterm.lua"
output_path = "~/.cache/dotfiles/colors_wezterm.lua"

[templates.zellij]
input_path = "~/.config/matugen/templates/dark/colors-zellij.kdl"
output_path = "~/.cache/dotfiles/hypr.kdl"
