theme = "tokyonight_storm"

[editor]
mouse = true
line-number = "relative"
cursorline = true
cursorcolumn = false
auto-completion = true
path-completion = true
auto-format = true
completion-timeout = 250
preview-completion-insert = false
completion-trigger-len = 2
completion-replace = false
auto-info = true
bufferline = "multiple"
color-modes = true
popup-border = "all"

[editor.statusline]
left = ["mode", "spacer", "version-control", "file-name", "read-only-indicator", "file-modification-indicator", "spinner"]
center = []
right = ["workspace-diagnostics","diagnostics" , "primary-selection-length", "selections", "register", "position-percentage", "position", "total-line-numbers", "file-encoding"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
